#!/bin/bash
DEVLIST=$@
for DEV in $DEVLIST
do
	VENDOR=$(cat /sys/bus/pci/devices/$DEV/vendor)
	DEVICE=$(cat /sys/bus/pci/devices/$DEV/device)
	if [ -e /sys/bus/pci/devices/$DEV/driver ]
	then
		echo $DEV > /sys/bus/pci/devices/$DEV/driver/unbind
	fi
	echo $VENDOR $DEVICE > /sys/bus/pci/drivers/vfio-pci/new_id
done

modprobe vfio-pci
