#!/bin/bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TOOLBOXLOC=$SCRIPTDIR #Override this if you feel like placing the toolbox elsewhere

. $TOOLBOXLOC/toolbox

PCIHEADS=`getPCIHeads`
LONGLIST=`getLongList "$PCIHEADS"`

echo "$LONGLIST"

echo "=======Reference======="
for PCIHEAD in $PCIHEADS
do
	lspci -vn | grep $PCIHEAD | awk '{print $1,$3}'
done
