#!/bin/bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TOOLBOXLOC=$SCRIPTDIR #Override this if you feel like placing the toolbox elsewhere

. $TOOLBOXLOC/toolbox

PCIHEADS=`getPCIHeads`
LONGLIST=`getLongList "$PCIHEADS"`

echo "======= Long list of VGA devices  ======="
echo "$LONGLIST"

echo "======= Short list of VGA devices ======="
for PCIHEAD in $PCIHEADS
do
	lspci -vn | grep $PCIHEAD | awk '{print $1,$3}'
done
