#!/bin/bash
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TOOLBOXLOC=$SCRIPTDIR #Override this if you feel like placing the toolbox elsewhere

. $TOOLBOXLOC/toolbox

echo "======= Detailed list of VGA devices  ======="
PCIHEADS=`getPCIHeads`
getDetailedList "$PCIHEADS"

echo
echo "======= Long list of VGA devices  ======="
PCIHEADS=`getPCIHeads`
getLongList "$PCIHEADS"

echo
echo "======= Short list of VGA devices ======="
getHeadList
