#!/bin/bash

getPCIHeads() {
	lspci -v | grep 'VGA' | awk '{print $1}' | sed 's/\..*$//g' | xargs
}
getHeadList() {
	PCIHEADS=`getPCIHeads`
	for PCIHEAD in $PCIHEADS
	do
        	lspci -vn | grep $PCIHEAD | awk '{print $1,$3}'
	done
}
getDetailedList() {
	IDLIST=`echo "$*" | sed "s/ /|/g"`
	lspci -vnn | awk "/$IDLIST/,/^$/"
}
getLongList() {
	DETAILEDLIST=`getDetailedList $*`
	IDLIST=`echo "$*" | sed "s/ /|/g"`
	echo "$DETAILEDLIST" | awk "/$IDLIST|Kernel driver/,/$/" | sed "s/\r\n/ /g"
}
getShortList() {
	getLongList "$*" | sed "s/\ .*\[\|\].*$/ /g"
}
extractShortList() {
	echo "$*" | sed "s/\ .*\[\|\].*$/ /g"
}
